server:
  # 开启优雅停机,默认IMMEDIATE是立即关机
  shutdown: graceful
spring:
  lifecycle:
    # 缓冲时间,默认时间为30S,意味着最多等待30S，超时无论线程任务是否执行完毕都会停机处理，一定要合理合理设置。
    timeout-per-shutdown-phase: 20s


management:
  endpoint:
    shutdown:
      # 启用shutdown
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      # 自定义管理端点的前缀(保证安全)
      base-path: /MyActuator
  server:
    # 自定义端口
    port: 9999
    # 不允许远程管理连接(不允许外部调用保证安全)
    address: 127.0.0.1